cache:
  key: ${CI_BUILD_REF_NAME}_1
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:tags:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build:library
  only:
    - /^v.*$/
  except:
    - branches
  artifacts:
    paths:
    - dist

deploy:tags:
  image: node:latest
  stage: deploy
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish dist/angular2-tinymce-lib
  only:
    - /^v.*$/
  except:
    - branches
  dependencies:
    - build:tags

build:master:
  image: node:latest
  stage: build
  script:
    - npm install
    - npm run build:library
    - npm run build
  only:
    - master
  artifacts:
    paths:
    - dist

deploy:master:
  image: node:latest
  stage: deploy
  script:
    - mv dist/index.html dist/200.html
    - PATH=$(npm bin):$PATH surge --project ./dist --domain angular2-tinymce.surge.sh
  only:
    - master
  dependencies:
    - build:master
